"use client";

import { useState } from "react";
import {
  INITIAL_BLIND_SHOT_DRAFT,
  confirmMeasuredTime,
  editMeasuredTime,
  editPrediction,
  hasUnsavedBlindProgress,
  isDraftComplete,
  lockPrediction,
  predictionError as computePredictionError,
  setMeasuredReleaseTime,
  targetError as computeTargetError,
  type BlindShotDraft,
} from "../lib/blindWeight";
import { formatReleaseTime, formatSigned, parseReleaseTime } from "../lib/timeInput";
import type { Handle, ShotType } from "../types";
import type { ShotEntryTarget } from "./ShotEntry";
import { surfaceClass } from "./Surface";

type BlindShotEntryProps = {
  onAddShot: (
    releaseTime: number,
    handle: Handle,
    shotType: ShotType | undefined,
    targetTimeOverride: number | undefined,
    predictedTime: number
  ) => void;
  target: ShotEntryTarget;
  onDraftStateChange: (hasUnsavedProgress: boolean) => void;
};

export default function BlindShotEntry({
  onAddShot,
  target,
  onDraftStateChange,
}: BlindShotEntryProps) {
  const [draft, setDraft] = useState<BlindShotDraft>(INITIAL_BLIND_SHOT_DRAFT);
  const [handle, setHandle] = useState<Handle>("in");
  const [predictedInput, setPredictedInput] = useState("");
  const [measuredInput, setMeasuredInput] = useState("");
  const [manualTargetInput, setManualTargetInput] = useState(
    target.value.toFixed(2)
  );

  // Adjust local state during render when a source-of-truth value changes
  // externally, rather than in an effect — see ShotEntry.tsx for the same
  // established pattern in this project.
  const [lastSeenTargetValue, setLastSeenTargetValue] = useState(target.value);

  if (target.value !== lastSeenTargetValue) {
    setLastSeenTargetValue(target.value);
    setManualTargetInput(target.value.toFixed(2));
  }

  const [lastSeenPhase, setLastSeenPhase] = useState(draft.phase);

  if (draft.phase !== lastSeenPhase) {
    setLastSeenPhase(draft.phase);

    if (draft.phase === "predict" && draft.predictedTime !== undefined) {
      setPredictedInput(draft.predictedTime.toFixed(2));
    }

    if (draft.phase === "measure" && draft.releaseTime !== undefined) {
      setMeasuredInput(draft.releaseTime.toFixed(2));
    }
  }

  function updateDraft(next: BlindShotDraft) {
    setDraft(next);
    onDraftStateChange(hasUnsavedBlindProgress(next));
  }

  function resolvedTargetTime(): number | null {
    if (!target.editable) return target.value;

    const parsed = parseReleaseTime(manualTargetInput);
    return parsed !== null && parsed > 0 ? parsed : null;
  }

  function handleLockPrediction() {
    const parsedTarget = resolvedTargetTime();

    if (parsedTarget === null) {
      alert("Please enter a valid target time.");
      return;
    }

    const parsedPrediction = parseReleaseTime(predictedInput);

    if (parsedPrediction === null || parsedPrediction <= 0) {
      alert("Please enter a valid predicted time.");
      return;
    }

    updateDraft(lockPrediction(draft, parsedPrediction));
  }

  function handleReviewShot() {
    const parsedMeasured = parseReleaseTime(measuredInput);

    if (parsedMeasured === null || parsedMeasured <= 0) {
      alert("Please enter a valid measured release time.");
      return;
    }

    const withMeasurement = setMeasuredReleaseTime(
      draft,
      parsedMeasured,
      "manual"
    );

    updateDraft(confirmMeasuredTime(withMeasurement));
  }

  function handleEditPrediction() {
    updateDraft(editPrediction(draft));
  }

  function handleEditMeasuredTime() {
    updateDraft(editMeasuredTime(draft));
  }

  function handleSaveShot() {
    if (!isDraftComplete(draft)) return;

    const targetTimeOverride = target.editable
      ? (resolvedTargetTime() ?? undefined)
      : undefined;

    onAddShot(
      draft.releaseTime,
      handle,
      undefined,
      targetTimeOverride,
      draft.predictedTime
    );

    setPredictedInput("");
    setMeasuredInput("");
    setHandle("in");
    updateDraft(INITIAL_BLIND_SHOT_DRAFT);
  }

  const targetTimeForDisplay = target.editable
    ? (resolvedTargetTime() ?? target.value)
    : target.value;

  return (
    <div className={surfaceClass("hero")}>
      <h2 className="text-xl font-semibold text-slate-900">
        Blind Weight Shot
      </h2>

      <div className={surfaceClass("inset", "mt-4")}>
        <div className="flex items-center justify-between gap-3">
          <p className="text-sm font-medium text-slate-700">Target</p>

          {target.autoGenerated && (
            <span className="rounded-full bg-slate-900 px-2 py-1 text-xs font-medium text-white">
              Auto
            </span>
          )}
        </div>

        {target.editable && draft.phase === "predict" ? (
          <input
            type="text"
            inputMode="decimal"
            aria-label="Target time"
            value={manualTargetInput}
            onChange={(event) => {
              const value = event.target.value;
              if (/^[0-9.,]*$/.test(value)) {
                setManualTargetInput(value);
              }
            }}
            className="mt-2 w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-lg text-slate-900 placeholder:text-slate-400"
          />
        ) : (
          <p className="mt-1 text-3xl font-semibold text-slate-900">
            {formatReleaseTime(targetTimeForDisplay)}
          </p>
        )}
      </div>

      {draft.phase === "predict" && (
        <>
          <p className="mt-4 text-sm text-slate-600">
            Play the shot, then estimate your release time before checking
            the timing system.
          </p>

          <div className="mt-4 flex gap-2">
            <button
              type="button"
              onClick={() => setHandle("in")}
              className={`flex-1 rounded-xl px-4 py-3 font-medium transition ${
                handle === "in"
                  ? "bg-slate-900 text-white"
                  : "bg-slate-200 text-slate-700"
              }`}
            >
              In Handle
            </button>

            <button
              type="button"
              onClick={() => setHandle("out")}
              className={`flex-1 rounded-xl px-4 py-3 font-medium transition ${
                handle === "out"
                  ? "bg-slate-900 text-white"
                  : "bg-slate-200 text-slate-700"
              }`}
            >
              Out Handle
            </button>
          </div>

          <label className="mt-4 block text-sm font-medium text-slate-700">
            What release time do you think you played?
          </label>

          <input
            type="text"
            inputMode="decimal"
            enterKeyHint="done"
            placeholder="Predicted Time"
            aria-label="Predicted time"
            value={predictedInput}
            onKeyDown={(event) => {
              if (event.key === "Enter") {
                event.preventDefault();
                handleLockPrediction();
              }
            }}
            onChange={(event) => {
              const value = event.target.value;
              if (/^[0-9.,]*$/.test(value)) {
                setPredictedInput(value);
              }
            }}
            className="mt-2 w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-lg text-slate-900 placeholder:text-slate-400"
          />

          <button
            type="button"
            onClick={handleLockPrediction}
            className="mt-4 w-full rounded-xl bg-slate-900 px-4 py-3 font-medium text-white transition hover:bg-slate-700"
          >
            Lock Prediction
          </button>
        </>
      )}

      {draft.phase === "measure" && draft.predictedTime !== undefined && (
        <>
          <div className={surfaceClass("inset", "mt-4")}>
            <p className="text-sm text-slate-500">Prediction locked</p>
            <p className="mt-1 text-2xl font-semibold text-slate-900">
              {formatReleaseTime(draft.predictedTime)}
            </p>
          </div>

          <p className="mt-4 text-sm text-slate-600">
            Now check the timing system and enter the measured release time.
          </p>

          <label className="mt-4 block text-sm font-medium text-slate-700">
            Measured Release Time
          </label>

          <input
            type="text"
            inputMode="decimal"
            enterKeyHint="done"
            placeholder="Measured Release Time"
            aria-label="Measured release time"
            value={measuredInput}
            onKeyDown={(event) => {
              if (event.key === "Enter") {
                event.preventDefault();
                handleReviewShot();
              }
            }}
            onChange={(event) => {
              const value = event.target.value;
              if (/^[0-9.,]*$/.test(value)) {
                setMeasuredInput(value);
              }
            }}
            className="mt-2 w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-lg text-slate-900 placeholder:text-slate-400"
          />

          <div className="mt-4 flex gap-2">
            <button
              type="button"
              onClick={handleEditPrediction}
              className="flex-1 rounded-xl bg-slate-200 px-4 py-3 font-medium text-slate-700 transition hover:bg-slate-300"
            >
              Edit Prediction
            </button>

            <button
              type="button"
              onClick={handleReviewShot}
              className="flex-1 rounded-xl bg-slate-900 px-4 py-3 font-medium text-white transition hover:bg-slate-700"
            >
              Review Shot
            </button>
          </div>
        </>
      )}

      {draft.phase === "review" &&
        draft.predictedTime !== undefined &&
        draft.releaseTime !== undefined &&
        (() => {
          const predictionErrorValue = computePredictionError(
            draft.predictedTime,
            draft.releaseTime
          );
          const targetErrorValue = computeTargetError(
            draft.releaseTime,
            targetTimeForDisplay
          );

          return (
            <>
              <div className="mt-4 grid grid-cols-2 gap-2">
                <ReviewMetric
                  label="Target"
                  value={formatReleaseTime(targetTimeForDisplay)}
                />
                <ReviewMetric
                  label="Prediction"
                  value={formatReleaseTime(draft.predictedTime)}
                />
                <ReviewMetric
                  label="Actual"
                  value={formatReleaseTime(draft.releaseTime)}
                />
                <ReviewMetric
                  label="Target Error"
                  value={`${formatSigned(targetErrorValue)}s`}
                />
              </div>

              <div className={surfaceClass("inset", "mt-2")}>
                <p className="text-sm text-slate-500">Prediction Error</p>
                <p className="mt-1 text-xl font-semibold text-slate-900">
                  {formatSigned(predictionErrorValue)}s
                </p>
                <p className="mt-1 text-xs text-slate-500">
                  {predictionErrorValue >= 0
                    ? "You believed you played slower than you actually did."
                    : "You believed you played faster than you actually did."}
                </p>
              </div>

              <div className="mt-4 flex gap-2">
                <button
                  type="button"
                  onClick={handleEditPrediction}
                  className="flex-1 rounded-xl bg-slate-200 px-4 py-3 font-medium text-slate-700 transition hover:bg-slate-300"
                >
                  Edit Prediction
                </button>

                <button
                  type="button"
                  onClick={handleEditMeasuredTime}
                  className="flex-1 rounded-xl bg-slate-200 px-4 py-3 font-medium text-slate-700 transition hover:bg-slate-300"
                >
                  Edit Measured Time
                </button>
              </div>

              <button
                type="button"
                onClick={handleSaveShot}
                disabled={!isDraftComplete(draft)}
                className="mt-4 w-full rounded-xl bg-slate-900 px-4 py-3 font-medium text-white transition hover:bg-slate-700 disabled:cursor-not-allowed disabled:bg-slate-300"
              >
                Save Shot & Continue
              </button>
            </>
          );
        })()}
    </div>
  );
}

type ReviewMetricProps = {
  label: string;
  value: string;
};

function ReviewMetric({ label, value }: ReviewMetricProps) {
  return (
    <div className={surfaceClass("inset")}>
      <p className="text-sm text-slate-500">{label}</p>
      <p className="mt-1 text-xl font-semibold text-slate-900">{value}</p>
    </div>
  );
}
