"use client";

import { useState } from "react";
import { formatReleaseTime, parseReleaseTime } from "../lib/timeInput";
import type { Handle, ShotType } from "../types";
import { surfaceClass } from "./Surface";

export type ShotEntryTarget = {
  value: number;
  editable: boolean;
  autoGenerated: boolean;
};

type ShotEntryProps = {
  onAddShot: (
    releaseTime: number,
    handle: Handle,
    shotType: ShotType,
    targetTimeOverride?: number
  ) => void;
  target: ShotEntryTarget;
  /**
   * "hero" (default) when this is the active capture task; "primary" when
   * Auto Capture is running and this becomes the secondary/fallback entry
   * path — see TrackerApp.tsx's Active Training surface hierarchy.
   */
  level?: "hero" | "primary";
};

export default function ShotEntry({
  onAddShot,
  target,
  level = "hero",
}: ShotEntryProps) {
  const [inputValue, setInputValue] = useState("");
  const [handle, setHandle] = useState<Handle>("in");
  const [shotType, setShotType] = useState<ShotType>("draw");
  const [manualTargetInput, setManualTargetInput] = useState(
    target.value.toFixed(2)
  );

  // Adjust local state during render when the source-of-truth target changes
  // externally (new block, or right after a shot was saved) — never while
  // the coach is mid-edit, since that only lives in local state until save.
  // This is the React-recommended way to reset state on a prop change,
  // without the extra render pass (and lint violation) an effect would add.
  const [lastSeenTargetValue, setLastSeenTargetValue] = useState(target.value);

  if (target.value !== lastSeenTargetValue) {
    setLastSeenTargetValue(target.value);
    setManualTargetInput(target.value.toFixed(2));
  }

  function handleAddShot() {
    const parsedValue = parseReleaseTime(inputValue);

    if (parsedValue === null) {
      alert("Please enter a valid release time.");
      return;
    }

    if (target.editable) {
      // No measurement-mode-specific range is enforced here on purpose —
      // there's no validated Hog-Hog target range in this project (see
      // variableTargets.ts), so Manual mode only checks that the value is a
      // usable positive number, not a sport-specific bound.
      const parsedTarget = parseReleaseTime(manualTargetInput);

      if (parsedTarget === null || parsedTarget <= 0) {
        alert("Please enter a valid target time.");
        return;
      }

      onAddShot(parsedValue, handle, shotType, parsedTarget);
    } else {
      onAddShot(parsedValue, handle, shotType);
    }

    setInputValue("");
  }

  return (
    <div className={surfaceClass(level)}>
      <h2 className="text-xl font-semibold text-slate-900">Add Shot</h2>

      <div className={surfaceClass("inset", "mt-4")}>
        <div className="flex items-center justify-between gap-3">
          <p className="text-sm font-medium text-slate-700">
            Target for Next Shot
          </p>

          {target.autoGenerated && (
            <span className="rounded-full bg-slate-900 px-2 py-1 text-xs font-medium text-white">
              Auto
            </span>
          )}
        </div>

        {target.editable ? (
          <input
            type="text"
            inputMode="decimal"
            value={manualTargetInput}
            onChange={(event) => {
              const value = event.target.value;
              const isValidInput = /^[0-9.,]*$/.test(value);

              if (isValidInput) {
                setManualTargetInput(value);
              }
            }}
            className="mt-2 w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-lg text-slate-900 placeholder:text-slate-400"
          />
        ) : (
          <p className="mt-1 text-3xl font-semibold text-slate-900">
            {formatReleaseTime(target.value)}
          </p>
        )}

        <p className="mt-2 text-xs text-slate-500">
          {target.editable
            ? "Coach target — edit before saving this shot."
            : target.autoGenerated
              ? "Generated automatically for this shot."
              : "Default target for this training block."}
        </p>
      </div>

      <input
        type="text"
        inputMode="decimal"
        enterKeyHint="done"
        placeholder="3.75 or 375"
        value={inputValue}
        onKeyDown={(event) => {
          if (event.key === "Enter") {
            event.preventDefault();
            handleAddShot();
          }
        }}
        onChange={(event) => {
          const value = event.target.value;
          const isValidInput = /^[0-9.,]*$/.test(value);

          if (isValidInput) {
            setInputValue(value);
          }
        }}
        className="mt-4 w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-lg text-slate-900 placeholder:text-slate-400"
      />

      <div className="mt-4 flex gap-2">
        <button
          type="button"
          onClick={() => setHandle("in")}
          className={`flex-1 rounded-xl px-4 py-3 font-medium transition ${
            handle === "in"
              ? "bg-slate-900 text-white"
              : "bg-slate-200 text-slate-700"
          }`}
        >
          In Handle
        </button>

        <button
          type="button"
          onClick={() => setHandle("out")}
          className={`flex-1 rounded-xl px-4 py-3 font-medium transition ${
            handle === "out"
              ? "bg-slate-900 text-white"
              : "bg-slate-200 text-slate-700"
          }`}
        >
          Out Handle
        </button>
      </div>

      <div className="mt-4 grid grid-cols-2 gap-2">
        {(["draw", "takeout"] as ShotType[]).map((type) => (
          <button
            key={type}
            type="button"
            onClick={() => setShotType(type)}
            className={`rounded-xl px-4 py-3 font-medium capitalize transition ${
              shotType === type
                ? "bg-slate-900 text-white"
                : "bg-slate-200 text-slate-700"
            }`}
          >
            {type}
          </button>
        ))}
      </div>

      <button
        type="button"
        onClick={handleAddShot}
        className="mt-4 w-full rounded-xl bg-slate-900 px-4 py-3 text-white transition hover:bg-slate-700"
      >
        Add Shot
      </button>
    </div>
  );
}
